### ISSUE TITLE
[BUG] Redirection still failed 

### ISSUE THREAD

**Issue by YGHS4** [zcyberseclab/zscan#27] opened 2024-12-04 08:27 UTC
### Current Behavior
"Fanwei e-message" redirect link still does not display the content after the jump.
![企业微信截图_17333003689864](https://github.com/user-attachments/assets/4e9a2b90-792f-4e3e-b76e-34f79c6d84c4)

### Expected Behavior
Some website redirection is still successful, for example "fanwei e-mobile" 1.183.16.238:8989.

### Steps To Reproduce
``` json
"emessage": {
    "body": [
      "emessage"
    ]
  }
```
``` go
go run .\cmd\main.go -target 101.200.140.240:9090
```

### Environment
Go: go1.22.2 windows/amd64
Zscan：v1.0.7

**Comment by YGHS4** [comment] 2024-12-04 08:51
### Other assets have the same question
![image](https://github.com/user-attachments/assets/2527f860-fbad-4a0a-9e10-695b980dd5c4)

### Steps To Reproduce
``` json
"feiyuxing-router": {
    "type": "router",
    "manufacturer": "avm",
    "body": [
      "飞鱼星路由器"
    ]
  }
```
``` go
go run .\cmd\main.g -target 111.160.2.118:8081
```

**Comment by superway117** [comment] 2024-12-05 03:36
redirect for  meta refresh redirect. fixed in funcion `checkURL`

**Comment by zcyberseclab** [comment] 2024-12-07 07:55
the following target are tested
- 111.160.2.118:8081
- 111.14.160.165:8081
- 101.200.140.240:9090
fixed. 

the root cause is that these url use meta refresh to redirect

**Closed as completed** 2024-12-07 13:54 UTC
